### PR TITLE
Adding 3 new tweaks - Pet AND Player Arena Match Limit adjuster. And spell over-cast window removal tweak.

### PR DESCRIPTION
**Pull request by EnragedWaters**
Hiya. This is EnragedWaters#8982 on discord. I wanted to file a suggestion but wanted to at least contribute to my own suggestion.
This suggestion/branch does the following:
1. Adds a game play tweak to adjust daily pet arena attempts - by default it's still 3 but it can be changed to 10 all the way to 100 in intervals of 10. Because of this tweak I also added in dialogue to Pet Arena Master to show how many match attempts the user still has left. 
2. Adds a convenience tweak to remove the spell over-cast confirmation window. 
Lemme know if these are OK - I'd love to occasionally submit more tweaks people could benefit from.

### CODE REVIEW

**Comment by Ruin0x11** [comment]
I think these are good additions. If I recall correctly, the omake line added something similar for spell overcasting through their "achievements" system.

However, there is a bug with the current set of changes: the definitions for the new tweak variables (`TWEAK_CONVENIENCE_REMOVE_OVER_CAST_CONFIRMATION`, `TWEAK_GAMEPLAY_PET_ARENA_INCREASED_MATCH_LIMIT`) are undefined, so they end up as `0`. They should be defined in the `defines/mod.hsp` file. (I was meaning to split it up into multiple files at some point, hence why I put it in another folder, but I never got around to it.)

**Comment by EnragedWaters** [comment]
woops, I forgot to upload the mod.hsp file! (I promise I tested these before hand lol) - lemme fix that real quick

**Comment by EnragedWaters** [comment]
Ok, think it's all fixed now. :> Still getting used to working with github branching.

**Comment by EnragedWaters** [comment]
I do have a question - I am working on a tweak for player Duel/Rumbles since I feel it's only appropriate after doing pet arena tweak and noticed basically
ADATA_ARENA_MATCHES_FOUGHT 39   //  is for Pet Arena

and if I wanted to do the same tweak like for pet arena, I would need:
#define global  ADATA_PLAYER_ARENA_DUELS_FOUGHT 40 
#define global  ADATA_PLAYER_ARENA_RUMBLES_FOUGHT 41

Since the game doesn't track the players daily duels/rumbles - only keeps track of time through ARENA_RENEW1 and ARENA_RENEW2

However, I feel the need to rename the Pet Arena Adata so Player And Pet are distinguishable - was wondering if there would be any issues adding new Adatas and as long as I replace the Pet Arena adata names correctly - if it should be ok?

**Comment by EnragedWaters** [comment]
UPDATE: I completed a 3rd tweak for Player Arena duels/rumbles and haven't had any issues during testing. I just felt it was appropriate since I already did the pet arena. 

1. Renames ADATA_ARENA_MATCHES_FOUGHT to ADATA_PET_ARENA_MATCHES_FOUGHT in the code to distinguish player and pet
2. Adds 2 new Adatas - ADATA_PLAYER_ARENA_DUELS_FOUGHT and ADATA_PLAYER_ARENA_RUMBLES_FOUGHT for keeping track since the game only tracks time since last match - unlike pet's daily match tracker. (Since the game already uses 2 different player arena time trackers - one for duels - and another for rumbles.)
3. It's a gameplay tweak done in intervals of 5 for both duels and rumbles since 5x2 evens out with the pet limit adjuster in how it's done in intervals of 10.

That's about it - I basically made it so Player Arena match limit works identical in principle to how Pet Arena does it.

**Comment by EnragedWaters** [comment]
I hope I ain't being over-whelming but I added:
 1. A fourth tweak to increase the number of hireable servants(doesn't increase limit, just better chance of not getting 5 maids in a row - very annoying), and added in baker, fisher, and food vendor if tweak is On.
 2. A console command for wizard called "add_attribute" which sets all stats, life/mana, and speed to 2000. I found it frustrating while in debug creating new characters who even with the "gain_exp" cheat were completely useless for testing - I might want to add in another console command later to learn/set all skills/spells to 2000 but at least this will help for now.

**Comment by Ruin0x11** [comment]
I would prefer additional tweaks besides the original two to be in a separate pull request. That's because I was just getting ready to merge this PR, but adding more code means I have to re-review things.

**Comment by EnragedWaters** [comment]
Will do. I will fix that right now.

**Pull request closed without merging**
